export enum NotificationTypeEnum {
    COMMENT_REPLY = 'COMMENT_REPLY',
    COMMENT_MENTION = 'COMMENT_MENTION',
    NEW_POST_COMMENT = 'NEW_POST_COMMENT',
    NEW_POST = 'NEW_POST',
    POST_COMMENT_RATINGS = 'POST_COMMENT_RATINGS'
}