export enum UserStatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DEACTIVATED = 'DEACTIVATED',
  RESTRICTED = 'RESTRICTED',
  DELETED = 'DELETED'
}

export enum UserTypeEnum {
  BASIC = 'BASIC',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN'
}
