export const STORE_NAME = "@WIK";

export const STORE_KEYS = {
    ACCESS_CODE: `${STORE_NAME}_ACCESS_CODE`,
    ACTIVE_USER: `${STORE_NAME}_ACTIVE_USER`,
    THEME: `${STORE_NAME}_THEME`,
    TEMP_EMAIL: `${STORE_NAME}_TEMP_EMAIL`,
    USER_SETTINGS: `${STORE_NAME}_USER_SETTINGS`
};
